[service]
name = "backend-laravel"

[build]
builder = "heroku/buildpacks:20"

[variables]

[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port ${PORT}"

[php]
extensions = [
  "intl",
  "zip"
]
